### ISSUE TITLE
centos base image

### ISSUE THREAD

**Issue by daveisfera** [rethinkdb/rethinkdb-dockerfiles#47]
Please add official tags using the `centos7` and `centos8` base images so they can be used as well ( https://github.com/rethinkdb/rethinkdb/issues/6772#issuecomment-562271994 )

Thanks for your work to get this project revived and working again!

**Comment by gabor-boros** [comment]
@daveisfera I did not forget you! I'll do it in the second week of January.

**Comment by daveisfera** [comment]
No rush! Thanks for being willing to do this and looking forward to using the 2.4 release with a centos base

**Comment by gabor-boros** [comment]
Hello @daveisfera,
The dockerfile is created in https://github.com/rethinkdb/rethinkdb-dockerfiles/commit/1af469291c979834826f4fc801fcd326abdd1b86. I'll open a PR for docker hub as well to make it available on their side as well 😊

**Comment by gabor-boros** [comment]
Here we go. The PR is created for the addition.

**Comment by daveisfera** [comment]
Thanks!

**Comment by gabor-boros** [comment]
@daveisfera I never had this long issues, but its finally solved: https://hub.docker.com/_/rethinkdb.

As the end result based on the extremely lot of discussions, CentOS8 and Debian Buster images are available for download. 😇 

I'll close this issue now, but if you disagree with that (because of lack of CentOS 7), please let me know, and I'll reopen the issue or feel free to open a new one.

**Comment by daveisfera** [comment]
CentOS 8 is great. Thanks again for all of the work to get this done!
